page_size: 10
server:
  servlet:
    context-path: /api/v1
app:
  jwtSecret: ======================BezKoder=Spring===========================

  jwtExpirationMs: 3600000
  jwtRefreshExpirationMs: 86400000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/noteninja
    password: wowlg147
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
